// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivrpjginwyoeyyfljzxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2cnBqZ2lud3lvZXl5ZmxqenhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MTM2NTAsImV4cCI6MjA2NDM4OTY1MH0.JMRHWYAB3dJJlvLRPxLcDBzGuSCwHnfe46OaCEw69CM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);